// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3s11NIC2P_BVMdnJq_OydELF1sjA2meg',
    appId: '1:8377448931:web:cb59ff91b78a5be88508d6',
    messagingSenderId: '8377448931',
    projectId: 'brownie-app-c3970',
    authDomain: 'brownie-app-c3970.firebaseapp.com',
    storageBucket: 'brownie-app-c3970.firebasestorage.app',
    measurementId: 'G-BEDVK8T8KK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzsX9oyMgxF6rS5-53hgkSt2QStCYNQRk',
    appId: '1:8377448931:android:67c6a9f2de1c84418508d6',
    messagingSenderId: '8377448931',
    projectId: 'brownie-app-c3970',
    storageBucket: 'brownie-app-c3970.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7uKtRWk5qzDQnEhzKfOZf_u02KGAnZqk',
    appId: '1:8377448931:ios:525623e790bc80f38508d6',
    messagingSenderId: '8377448931',
    projectId: 'brownie-app-c3970',
    storageBucket: 'brownie-app-c3970.firebasestorage.app',
    iosBundleId: 'com.example.brownieApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7uKtRWk5qzDQnEhzKfOZf_u02KGAnZqk',
    appId: '1:8377448931:ios:525623e790bc80f38508d6',
    messagingSenderId: '8377448931',
    projectId: 'brownie-app-c3970',
    storageBucket: 'brownie-app-c3970.firebasestorage.app',
    iosBundleId: 'com.example.brownieApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3s11NIC2P_BVMdnJq_OydELF1sjA2meg',
    appId: '1:8377448931:web:617837626314a5088508d6',
    messagingSenderId: '8377448931',
    projectId: 'brownie-app-c3970',
    authDomain: 'brownie-app-c3970.firebaseapp.com',
    storageBucket: 'brownie-app-c3970.firebasestorage.app',
    measurementId: 'G-NL1RM9DW1L',
  );
}
